# -*- coding: utf-8 -*-
"""NLP_PR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSYphXZ7qfGusz8pP2PfgeooT4bQDP1b

#**🚨 Public Information Prioritizer Using Natural Language Processing**

**Mini NLP Project**

**Objective:**  
To develop an NLP-based system that analyzes public information and determines its category, crisis type, urgency, action requirement, promotional status, and final priority.

**Techniques Used:**
- Text Preprocessing
- TF-IDF Feature Extraction
- Logistic Regression
- Multinomial Naive Bayes
- Rule-Based NLP
- Confusion Matrix Evaluation

**Datasets:**
- News Article Categories Dataset
- Crisis Dataset

**1. Problem Statement**

Large amounts of public information such as news articles, emergency alerts, government notices, educational announcements, job notifications, and promotional messages are generated every day.

It can be difficult for people to quickly identify:

- What type of information they are reading
- Whether it is related to a crisis
- How urgent the information is
- Whether any action is required
- Whether the message is promotional
- Which information should receive higher priority

### Proposed Solution

This project develops a **Public Information Prioritizer using Natural Language Processing (NLP)**.

The system accepts a text message, news article, alert, or public notice and analyzes it using a combination of **machine learning and rule-based NLP techniques**.

The system produces:

1. Information category
2. Crisis status and crisis type
3. Urgency level
4. Action-required status
5. Promotional status
6. Final priority level

**2. Objectives**

The main objectives of this project are:

1. To preprocess and clean textual public information using NLP techniques.
2. To classify news articles into their respective categories using machine learning.
3. To identify the type of crisis mentioned in emergency-related information.
4. To estimate the urgency level of a message using rule-based NLP.
5. To determine whether an action is required from the reader.
6. To identify promotional or advertisement-related content.
7. To combine these outputs to calculate a final priority level.
8. To evaluate the machine learning components using accuracy, precision, recall, F1-score, and confusion matrices.
9. To compare different traditional machine learning approaches and select the better-performing model.

**3. Methodology**

The proposed system follows a hybrid NLP architecture combining **machine learning classification** with **rule-based NLP techniques**.

**Overall Workflow **

**Public Information**  
↓  
**Text Preprocessing**  
↓  
**Crisis / Promotion Detection**  
↓  
**Information Classification**  
↓  
**Urgency Detection**  
↓  
**Action Detection**  
↓  
**Priority Calculation**  
↓  
**Final Analysis Result**

**Machine Learning Components**

- **TF-IDF** is used to convert text into numerical features.
- **Logistic Regression** is used for news-category classification.
- **Logistic Regression** is also used for crisis-type classification.
- **Multinomial Naive Bayes** is evaluated as a comparison model for news classification.

**Rule-Based Components**

Rule-based NLP is used for:

- Crisis keyword detection
- Urgency detection
- Action-required detection
- Promotional-content detection
- Final priority calculation

This hybrid approach makes the system both **data-driven and interpretable**.

**4. Datasets**

This project uses two datasets to build different components of the Public Information Prioritizer.

**Dataset 1 — News Article Categories**

The News Article Categories dataset contains **6,877 records** with the following fields:

- `category` — target class
- `title` — news article title
- `body` — news article content

The dataset contains **14 news categories**:

- ARTS & CULTURE
- BUSINESS
- COMEDY
- CRIME
- EDUCATION
- ENTERTAINMENT
- ENVIRONMENT
- MEDIA
- POLITICS
- RELIGION
- SCIENCE
- SPORTS
- TECH
- WOMEN

After removing **28 exact duplicate records**, **6,849 records** were used for the final classification experiment.

**Dataset 2 — Crisis Dataset**

The Crisis dataset contains **2,345 records** and includes:

- `tweet_id`
- `user_id`
- `timestamp`
- `text`
- `crisis_type`
- `location`
- `relevance_label`
- `urgency_label`
- `informative_label`

The dataset contains **7 crisis types**:

- Earthquake
- Explosion
- Fire
- Flood
- Hurricane
- Landslide
- Pandemic

### Dataset Limitation

The crisis dataset contains a high number of repeated text entries. Therefore, a **group-aware train/test split** was used for crisis-type classification to prevent the same text from appearing in both training and testing sets.

The urgency labels also showed substantial inconsistency across repeated texts. Therefore, an ML-based urgency classifier was evaluated experimentally but was **not selected for the final system**.

**5. News Article Category Classification**

The first machine learning component classifies public information into one of the 14 news categories.

The following steps are performed:

1. Load and inspect the dataset
2. Explore the category distribution
3. Combine title and body text
4. Clean and preprocess the text
5. Remove exact duplicate records
6. Split the data into training and testing sets
7. Convert text into TF-IDF features
8. Train classification models
9. Compare model performance
10. Evaluate the selected model using a confusion matrix
"""

import pandas as pd
import numpy as np
import re
import csv

print("Libraries imported successfully!")

import os

print(os.listdir("/content"))

import csv
import pandas as pd

file_path = "/content/news-article-categories.csv"

rows = []

with open(file_path, "r", encoding="utf-8", errors="replace", newline="") as f:
    reader = csv.reader(f)

    for row in reader:
        if len(row) == 3:
            rows.append(row)

news_df = pd.DataFrame(
    rows[1:],
    columns=rows[0]
)

print("Dataset loaded successfully!")
print("Shape:", news_df.shape)
print("\nColumns:", news_df.columns.tolist())

print("First 5 rows:")
display(news_df.head())

print("\nMissing values:")
print(news_df.isnull().sum())

print("\nNumber of categories:")
print(news_df["category"].nunique())

print("\nCategory distribution:")
print(news_df["category"].value_counts())

# Fill any missing body values
news_df["body"] = news_df["body"].fillna("")

# Combine title and body
news_df["combined_text"] = (
    news_df["title"].astype(str) + " " +
    news_df["body"].astype(str)
)

print("Combined text created successfully!")
print(news_df[["category", "combined_text"]].head())

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

# Apply text cleaning
news_df["clean_text"] = news_df["combined_text"].apply(clean_text)

print("Text preprocessing completed!")
print("\nOriginal:")
print(news_df["combined_text"].iloc[0][:300])

print("\nCleaned:")
print(news_df["clean_text"].iloc[0][:300])

# Check duplicates before removing them
duplicates = news_df.duplicated(subset=["title", "body"]).sum()

print("Duplicate articles found:", duplicates)

# Remove exact duplicate articles
news_df = news_df.drop_duplicates(
    subset=["title", "body"]
).reset_index(drop=True)

print("Dataset shape after removing duplicates:", news_df.shape)

print("Number of categories:", news_df["category"].nunique())

from sklearn.model_selection import train_test_split

# Input text
X = news_df["clean_text"]

# Target category
y = news_df["category"]

# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Training classes:", y_train.nunique())
print("Testing classes:", y_test.nunique())

from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF vectorizer
tfidf = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

# Learn vocabulary from training data
X_train_tfidf = tfidf.fit_transform(X_train)

# Transform test data using the same vocabulary
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF completed successfully!")
print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Create Logistic Regression model
category_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Train the model
category_model.fit(X_train_tfidf, y_train)

# Predict test data
y_pred = category_model.predict(X_test_tfidf)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Logistic Regression Accuracy:", round(accuracy, 4))

# Detailed evaluation
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

from sklearn.metrics import f1_score

print("y_test size:", len(y_test))
print("y_pred size:", len(y_pred))
print("News accuracy:", accuracy_score(y_test, y_pred))
print("News macro F1:", f1_score(y_test, y_pred, average="macro"))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# Get category names
categories = sorted(y_test.unique())

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=categories)

# Plot confusion matrix
plt.figure(figsize=(8, 6))
plt.imshow(cm)

plt.xticks(
    range(len(categories)),
    categories,
    rotation=90
)

plt.yticks(
    range(len(categories)),
    categories
)

plt.xlabel("Predicted Category")
plt.ylabel("Actual Category")
plt.title("Confusion Matrix - Logistic Regression")

plt.colorbar()

plt.tight_layout()
plt.show()

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Create Naive Bayes model
nb_model = MultinomialNB()

# Train the model
nb_model.fit(X_train_tfidf, y_train)

# Predict test data
nb_pred = nb_model.predict(X_test_tfidf)

# Calculate accuracy
nb_accuracy = accuracy_score(y_test, nb_pred)

print("Multinomial Naive Bayes Accuracy:", round(nb_accuracy, 4))

print("\nClassification Report:")
print(classification_report(y_test, nb_pred))

nb_macro_f1 = f1_score(y_test, nb_pred, average="macro")

print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))
print("Naive Bayes Macro F1:", nb_macro_f1)

"""### 5.2 Model Comparison

Two traditional machine learning classifiers were evaluated using the same TF-IDF representation:

- Logistic Regression
- Multinomial Naive Bayes

Both models were trained and tested using the same training and testing data.

The models are compared using accuracy and macro F1-score. Macro F1-score gives equal importance to all 14 news categories.

Logistic Regression achieved better performance and was therefore selected as the final model for news-category classification.
"""

comparison_df = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Multinomial Naive Bayes"
    ],
    "Accuracy": [
        accuracy,
        nb_accuracy
    ],
    "Macro F1": [
        f1_score(y_test, y_pred, average="macro"),
        nb_macro_f1
    ]
})

display(comparison_df)

print("\nSelected Model: Logistic Regression")
print("Reason: It achieved higher accuracy and macro F1-score.")

"""**6. Crisis Information Classification**

The second dataset is used to identify whether public information is related to a crisis and, if so, determine the specific crisis type.

The crisis classification component follows these steps:

1. Load and explore the crisis dataset
2. Examine crisis-type and other label distributions
3. Check duplicate and conflicting text labels
4. Preprocess the crisis text
5. Apply a group-aware train/test split
6. Extract TF-IDF features
7. Train a Logistic Regression classifier
8. Evaluate the model using accuracy, precision, recall, F1-score, and confusion matrix
"""

# Load the crisis dataset

crisis_df = pd.read_csv("/content/crisis.csv")

print("Crisis dataset loaded successfully!")

print("Shape:", crisis_df.shape)

print("\nColumns:")
print(crisis_df.columns.tolist())

print("\nFirst 5 rows:")
display(crisis_df.head())

print("Crisis Type Distribution:")
print(crisis_df["crisis_type"].value_counts())

print("\nUrgency Distribution:")
print(crisis_df["urgency_label"].value_counts())

print("\nRelevance Distribution:")
print(crisis_df["relevance_label"].value_counts())

print("\nInformative Distribution:")
print(crisis_df["informative_label"].value_counts())

print("\nMissing Values:")
print(crisis_df.isnull().sum())

"""**6.1 Data Quality and Duplicate Analysis**

Before training the crisis classifier, duplicate text entries and label consistency were examined.

This step is important because repeated text can cause data leakage if identical texts are randomly divided between training and testing sets.

The analysis also checks whether the same text is associated with different crisis types, urgency labels, or relevance labels.
"""

# Check duplicate text
duplicate_texts = crisis_df["text"].duplicated().sum()

print("Duplicate text rows:", duplicate_texts)

# Check whether the same text has different crisis types
crisis_type_conflicts = (
    crisis_df.groupby("text")["crisis_type"]
    .nunique()
)

# Check whether the same text has different urgency labels
urgency_conflicts = (
    crisis_df.groupby("text")["urgency_label"]
    .nunique()
)

# Check whether the same text has different relevance labels
relevance_conflicts = (
    crisis_df.groupby("text")["relevance_label"]
    .nunique()
)

print(
    "Texts with conflicting crisis types:",
    (crisis_type_conflicts > 1).sum()
)

print(
    "Texts with conflicting urgency labels:",
    (urgency_conflicts > 1).sum()
)

print(
    "Texts with conflicting relevance labels:",
    (relevance_conflicts > 1).sum()
)

"""**6.2 Crisis Text Preprocessing**

The crisis text is cleaned before feature extraction and classification.

The preprocessing includes:

- Converting text to lowercase
- Removing URLs
- Removing user mentions
- Removing unnecessary extra spaces

The cleaned text is then used for TF-IDF feature extraction and machine learning.
"""

# Make sure crisis text is treated as string
crisis_df["text"] = crisis_df["text"].astype(str)

# Clean crisis text
def clean_crisis_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

crisis_df["clean_text"] = crisis_df["text"].apply(clean_crisis_text)

print("Crisis text preprocessing completed!")

print("\nOriginal text:")
print(crisis_df["text"].iloc[0])

print("\nCleaned text:")
print(crisis_df["clean_text"].iloc[0])

"""**6.3 Group-Aware Train/Test Split**

The crisis dataset contains many repeated text entries. A random train/test split could place the same text in both sets and lead to data leakage.Therefore, a group-aware split is used, where identical texts are kept within the same group.This ensures that the model is evaluated on texts that were not seen in the training set.
"""

from sklearn.model_selection import GroupShuffleSplit

# Input and target
X_crisis = crisis_df["clean_text"]
y_crisis = crisis_df["crisis_type"]

# Original text is used as the group
# This keeps identical texts together
groups = crisis_df["text"]

# Group-aware train/test split
gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(X_crisis, y_crisis, groups=groups)
)

X_crisis_train = X_crisis.iloc[train_idx]
X_crisis_test = X_crisis.iloc[test_idx]

y_crisis_train = y_crisis.iloc[train_idx]
y_crisis_test = y_crisis.iloc[test_idx]

print("Training samples:", len(X_crisis_train))
print("Testing samples:", len(X_crisis_test))

print("Training classes:", y_crisis_train.nunique())
print("Testing classes:", y_crisis_test.nunique())

# Verify that no original text appears in both sets
train_texts = set(crisis_df["text"].iloc[train_idx])
test_texts = set(crisis_df["text"].iloc[test_idx])

print("Common texts between train and test:", len(train_texts & test_texts))

from sklearn.feature_extraction.text import TfidfVectorizer

crisis_tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_crisis_train_tfidf = crisis_tfidf.fit_transform(X_crisis_train)
X_crisis_test_tfidf = crisis_tfidf.transform(X_crisis_test)

print("Training TF-IDF shape:", X_crisis_train_tfidf.shape)
print("Testing TF-IDF shape:", X_crisis_test_tfidf.shape)

"""**6.4 Crisis Type Classification**

TF-IDF features are used to represent the cleaned crisis-related text numerically.A Logistic Regression classifier is then trained to identify the type of crisis.

The model classifies the text into seven crisis categories:

- Earthquake
- Explosion
- Fire
- Flood
- Hurricane
- Landslide
- Pandemic

The model performance is evaluated using accuracy, precision, recall, F1-score, and a confusion matrix.

**6.5 Crisis Type Model Evaluation**

The crisis-type classifier is evaluated using accuracy, precision, recall, and F1-score.

A confusion matrix is also used to examine the classification results for each crisis category.

The model achieved **100% accuracy and a macro F1-score of 1.00** on the group-aware test set.

Although the result is excellent, the structured and repetitive nature of the dataset should be considered when interpreting this performance.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

crisis_type_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

crisis_type_model.fit(
    X_crisis_train_tfidf,
    y_crisis_train
)

crisis_type_pred = crisis_type_model.predict(
    X_crisis_test_tfidf
)

crisis_type_accuracy = accuracy_score(
    y_crisis_test,
    crisis_type_pred
)

print("Crisis Type Accuracy:", round(crisis_type_accuracy, 4))
print("\nClassification Report:")
print(classification_report(y_crisis_test, crisis_type_pred))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

plt.figure(figsize=(8, 6))

ConfusionMatrixDisplay.from_predictions(
    y_crisis_test,
    crisis_type_pred,
    xticks_rotation=45
)

plt.title("Crisis Type Classification - Confusion Matrix")
plt.tight_layout()
plt.show()

urgency_summary = (
    crisis_df.groupby("text")["urgency_label"]
    .agg(["count", "nunique", lambda x: x.value_counts().index[0]])
)

urgency_summary.columns = [
    "number_of_rows",
    "number_of_labels",
    "majority_label"
]

print(urgency_summary.head(10))

print("\nUnique texts:", len(urgency_summary))
print("Texts with conflicting urgency labels:",
      (urgency_summary["number_of_labels"] > 1).sum())

from collections import Counter

tie_count = 0
tie_examples = []

for text, labels in crisis_df.groupby("text")["urgency_label"]:
    counts = Counter(labels)
    max_count = max(counts.values())
    winners = [label for label, count in counts.items() if count == max_count]

    if len(winners) > 1:
        tie_count += 1
        if len(tie_examples) < 10:
            tie_examples.append((text[:80], dict(counts), winners))

print("Texts with tied majority labels:", tie_count)

print("\nExamples of ties:")
for example in tie_examples:
    print(example)

# Find texts with an unambiguous majority urgency label

usable_urgency = []

for text, labels in crisis_df.groupby("text")["urgency_label"]:
    counts = labels.value_counts()

    # Keep only if there is one clear majority label
    if len(counts) == 1 or counts.iloc[0] > counts.iloc[1]:
        usable_urgency.append({
            "text": text,
            "urgency_label": counts.index[0]
        })

urgency_df = pd.DataFrame(usable_urgency)

print("Total unique texts:", crisis_df["text"].nunique())
print("Usable texts with clear majority:", len(urgency_df))
print("Excluded tied texts:",
      crisis_df["text"].nunique() - len(urgency_df))

print("\nUrgency label distribution:")
print(urgency_df["urgency_label"].value_counts())

from sklearn.model_selection import train_test_split

X_urgency = urgency_df["text"]
y_urgency = urgency_df["urgency_label"]

X_urgency_train, X_urgency_test, y_urgency_train, y_urgency_test = train_test_split(
    X_urgency,
    y_urgency,
    test_size=0.20,
    random_state=42,
    stratify=y_urgency
)

print("Training samples:", len(X_urgency_train))
print("Testing samples:", len(X_urgency_test))
print("Training classes:", y_urgency_train.nunique())
print("Testing classes:", y_urgency_test.nunique())

urgency_tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=1,
    sublinear_tf=True
)

X_urgency_train_tfidf = urgency_tfidf.fit_transform(X_urgency_train)
X_urgency_test_tfidf = urgency_tfidf.transform(X_urgency_test)

print("Training TF-IDF shape:", X_urgency_train_tfidf.shape)
print("Testing TF-IDF shape:", X_urgency_test_tfidf.shape)

"""**7. Urgency Classification Experiment**

The crisis dataset also contains urgency labels: Low, Medium, and High.An ML-based urgency classifier was experimentally trained using TF-IDF features and Logistic Regression.
However, the repeated text entries contained inconsistent urgency labels. Therefore, the ML model achieved only **32.35% accuracy** and a **macro F1-score of 0.30**.Since this performance was close to random classification for three classes, the ML urgency model was not selected for the final system.Instead, a transparent rule-based NLP approach was used for urgency detection.
"""

urgency_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

urgency_model.fit(
    X_urgency_train_tfidf,
    y_urgency_train
)

urgency_pred = urgency_model.predict(
    X_urgency_test_tfidf
)

urgency_accuracy = accuracy_score(
    y_urgency_test,
    urgency_pred
)

print("Urgency Accuracy:", round(urgency_accuracy, 4))
print("\nClassification Report:")
print(classification_report(
    y_urgency_test,
    urgency_pred
))

"""**8. Rule-Based NLP Components**

Since the urgency ML experiment showed low performance, rule-based NLP techniques are used in the final system.

Keyword-based rules are used to identify:

- Crisis-related information
- Urgency level
- Whether an action is required
- Promotional or advertisement content

These rules make the system simple, transparent, and easy to interpret.

**8.1 Crisis Detection**

The system first checks whether the input text is related to a crisis.A predefined set of crisis-related keywords is used to identify terms associated with events such as earthquakes, floods, fires, hurricanes, landslides, explosions, and pandemics.If a crisis is detected, the text is passed to the crisis-type machine learning classifier.
"""

crisis_keywords = [
    "earthquake",
    "aftershock",
    "explosion",
    "blast",
    "fire",
    "wildfire",
    "flood",
    "flooding",
    "hurricane",
    "cyclone",
    "landslide",
    "mudslide",
    "pandemic",
    "epidemic",
    "covid",
    "evacuate",
    "evacuation",
    "disaster",
    "rescue",
    "emergency",
    "tsunami",
    "collapse"
]

def detect_crisis(text):
    text = clean_crisis_text(text)

    for keyword in crisis_keywords:
        if keyword in text:
            return "Crisis"

    return "Not Crisis"


print(detect_crisis(
    "A powerful earthquake has struck the region."
))

print(detect_crisis(
    "The government announced a new education policy."
))

print(detect_crisis(
    "Scientists published a new study about climate change."
))

"""**8.2 Urgency Detection**

The urgency level is determined using predefined keywords.

The system assigns three urgency levels:

- **High** — emergency or immediate-response terms are detected
- **Medium** — warning, risk, preparation, or caution-related terms are detected
- **Low** — no high- or medium-urgency terms are detected

This rule-based approach provides an interpretable urgency estimate.
"""

high_urgency_words = [
    "emergency",
    "evacuate",
    "evacuation",
    "warning",
    "alert",
    "critical",
    "danger",
    "urgent",
    "immediately",
    "life-threatening",
    "rescue",
    "disaster"
]

medium_urgency_words = [
    "advisory",
    "caution",
    "risk",
    "possible",
    "expected",
    "prepare",
    "prepared",
    "monitor",
    "concern"
]

def detect_urgency(text):
    text = clean_crisis_text(text)

    high_score = sum(word in text for word in high_urgency_words)
    medium_score = sum(word in text for word in medium_urgency_words)

    if high_score >= 1:
        return "High"
    elif medium_score >= 1:
        return "Medium"
    else:
        return "Low"

print(detect_urgency(
    "Emergency warning issued. Residents must evacuate immediately."
))

print(detect_urgency(
    "Authorities issued an advisory about possible flooding."
))

print(detect_urgency(
    "Officials reported normal conditions in the region."
))

"""**8.3 Action Required Detection**

The system determines whether the reader needs to take any action based on action-related keywords and phrases.

Examples include terms such as:

- evacuate
- avoid
- contact
- register
- apply
- submit
- deadline
- prepare
- follow

If an action-related term is detected, the system marks the information as **Yes**; otherwise, it marks it as **No**.
"""

action_words = [
    "evacuate",
    "evacuation",
    "avoid",
    "stay away",
    "do not",
    "don't",
    "must",
    "required",
    "call",
    "contact",
    "register",
    "apply",
    "submit",
    "deadline",
    "attend",
    "report",
    "prepare",
    "wear",
    "follow",
    "leave",
    "seek"
]

def detect_action_required(text):
    text = clean_crisis_text(text)

    for phrase in action_words:
        if phrase in text:
            return "Yes"

    return "No"


print(detect_action_required(
    "Residents must evacuate immediately and stay away from the area."
))

print(detect_action_required(
    "The government announced a new education policy today."
))

"""**8.4 Promotional Content Detection**

The system identifies whether the input contains promotional or advertisement-related content.

A predefined set of promotional keywords and phrases is used, such as:

- buy
- sale
- discount
- offer
- deal
- coupon
- sponsored
- advertisement
- promotion
- limited time
- free shipping

If a promotional term is detected, the text is classified as **Advertisement/Promotion**; otherwise, it is classified as **Not Promotional**.
"""

promotion_words = [
    "buy",
    "sale",
    "discount",
    "offer",
    "deal",
    "coupon",
    "shop",
    "purchase",
    "subscribe",
    "sponsored",
    "advertisement",
    "advertising",
    "promotion",
    "promo",
    "limited time",
    "free shipping"
]

def detect_promotion(text):
    text = clean_crisis_text(text)

    for phrase in promotion_words:
        if phrase in text:
            return "Advertisement/Promotion"

    return "Not Promotional"


print(detect_promotion(
    "Limited time offer! Buy now and get 50% discount."
))

print(detect_promotion(
    "Heavy rainfall warning issued across the district."
))

"""**8.5 Priority Calculation**

The final priority level is calculated by combining the detected crisis status, urgency level, action requirement, and promotional status.

The system assigns four priority levels:

- **Critical** — high-urgency crisis information requiring immediate action
- **High** — high-urgency information or medium-urgency information requiring action
- **Medium** — medium-urgency information or information requiring action
- **Low** — low-urgency information that does not require action

Promotional content is assigned a **Low** priority because it does not represent urgent public information.
"""

def calculate_priority(crisis_status, urgency, action_required, promotional):

    if promotional == "Advertisement/Promotion":
        return "Low"

    if (
        crisis_status == "Crisis"
        and urgency == "High"
        and action_required == "Yes"
    ):
        return "Critical"

    if (
        urgency == "High"
        or (urgency == "Medium" and action_required == "Yes")
    ):
        return "High"

    if urgency == "Medium" or action_required == "Yes":
        return "Medium"

    return "Low"

calculate_priority("Crisis", "High", "Yes", "Not Promotional")

test_inputs = [
    "Flash flood warning issued. Residents must evacuate immediately.",
    "The government announced a new education policy for students.",
    "Limited time offer! Buy now and get 50% discount.",
    "Heavy rainfall is expected in the region. Residents should prepare.",
    "Scientists published a new study about climate change."
]

for text in test_inputs:
    urgency = detect_urgency(text)
    action = detect_action_required(text)
    promotion = detect_promotion(text)

    print("\nText:", text)
    print("Urgency:", urgency)
    print("Action Required:", action)
    print("Promotion:", promotion)

"""**9. Complete NLP Prediction Pipeline**

The complete prediction pipeline combines all the machine learning and rule-based components developed in the project.

For a given input text, the system:

1. Detects promotional content.
2. Checks whether the text is crisis-related.
3. Classifies the crisis type if a crisis is detected.
4. Classifies the news category for non-crisis, non-promotional content.
5. Determines the urgency level.
6. Detects whether an action is required.
7. Calculates the final priority level.

The final output provides a structured analysis of the input information.
"""

import os

saved_files = [
    "news_category_model.pkl",
    "news_category_tfidf.pkl",
    "crisis_type_model.pkl",
    "crisis_type_tfidf.pkl"
]

for file in saved_files:
    print(file, "→", "Exists" if os.path.exists(file) else "Missing")

def predict_information(text):
    cleaned_text = clean_crisis_text(text)

    promotion = detect_promotion(cleaned_text)
    crisis_status = detect_crisis(cleaned_text)

    if crisis_status == "Crisis":
        crisis_input = crisis_tfidf.transform([cleaned_text])
        crisis_type = crisis_type_model.predict(crisis_input)[0]
        news_category = "N/A"
    elif promotion == "Advertisement/Promotion":
        crisis_type = "N/A"
        news_category = "ADVERTISEMENT"
    else:
        crisis_type = "N/A"
        news_input = tfidf.transform([cleaned_text])
        news_category = category_model.predict(news_input)[0]

    urgency = detect_urgency(cleaned_text)
    action = detect_action_required(cleaned_text)

    priority = calculate_priority(
        crisis_status,
        urgency,
        action,
        promotion
    )

    return {
        "Crisis Status": crisis_status,
        "Crisis Type": crisis_type,
        "News Category": news_category,
        "Urgency": urgency,
        "Action Required": action,
        "Promotion": promotion,
        "Final Priority": priority
    }

test_messages = [
    "A powerful earthquake has struck the region. Residents must evacuate immediately.",
    "Flash flood warning issued. Residents are advised to evacuate.",
    "The government announced a new education policy for college students.",
    "Limited time sale! Buy our products today and get 50% discount.",
    "Heavy rainfall is expected tomorrow. Residents should prepare for possible flooding.",
    "Scientists published a new study about climate change."
]

for i, message in enumerate(test_messages, 1):
    print(f"\nTEST {i}")
    print("Message:", message)
    print(predict_information(message))

test_inputs = [
    "A powerful earthquake has struck the region. Residents must evacuate immediately.",
    "Flash flood warning issued. Residents are advised to evacuate.",
    "The government announced a new education policy for college students.",
    "Limited time sale! Buy our products today and get 50% discount.",
    "Heavy rainfall is expected tomorrow. Residents should prepare for possible flooding.",
    "Scientists published a new study about climate change."
]

for i, text in enumerate(test_inputs, 1):
    print(f"\n{'='*60}")
    print(f"TEST {i}")
    print(f"Input: {text}")
    print("-" * 60)

    result = predict_information(text)

    for key, value in result.items():
        print(f"{key}: {value}")

import joblib
import os

# Save trained models and vectorizers
joblib.dump(category_model, "/content/news_category_model.pkl")
joblib.dump(tfidf, "/content/news_category_tfidf.pkl")

joblib.dump(crisis_type_model, "/content/crisis_type_model.pkl")
joblib.dump(crisis_tfidf, "/content/crisis_type_tfidf.pkl")

print("All project models saved successfully!")

print("\nSaved files:")
for file in [
    "news_category_model.pkl",
    "news_category_tfidf.pkl",
    "crisis_type_model.pkl",
    "crisis_type_tfidf.pkl"
]:
    print(file, "→", "Exists" if os.path.exists("/content/" + file) else "Missing")

"""**9.1 Interactive Prediction**

The system provides an interactive interface where the user can enter a news article, emergency alert, or public notice.

The entered text is passed through the complete NLP prediction pipeline, and the system displays:

- Crisis Status
- Crisis Type
- News Category
- Urgency
- Action Required
- Promotion Status
- Final Priority

This allows the developed NLP system to be tested with new, unseen text inputs.
"""

def run_project():
    print("=" * 70)
    print("🚨 PUBLIC INFORMATION PRIORITIZER USING NLP")
    print("=" * 70)

    text = input("\nEnter a news article, alert, notice, or message:\n> ")

    if not text.strip():
        print("\nPlease enter some text.")
        return

    result = predict_information(text)

    print("\n" + "=" * 70)
    print("📊 ANALYSIS RESULT")
    print("=" * 70)

    for key, value in result.items():
        print(f"{key}: {value}")

    print("=" * 70)


print("Interactive project demo created successfully!")

run_project()

"""**10. Results and Evaluation**

The performance of the machine learning components is evaluated using accuracy and macro F1-score.

The results of the different experiments are compared to determine which models are suitable for the final system.

The evaluation also includes confusion matrices to understand the classification performance across individual classes.
"""

# Final model evaluation summary
print("=" * 70)
print("📊 FINAL MODEL EVALUATION")
print("=" * 70)

news_accuracy = accuracy_score(y_test, y_pred)
news_macro_f1 = f1_score(y_test, y_pred, average="macro")

crisis_accuracy = accuracy_score(
    y_crisis_test,
    crisis_type_pred
)
crisis_macro_f1 = f1_score(
    y_crisis_test,
    crisis_type_pred,
    average="macro"
)

urgency_accuracy = accuracy_score(
    y_urgency_test,
    urgency_pred
)
urgency_macro_f1 = f1_score(
    y_urgency_test,
    urgency_pred,
    average="macro"
)

print("\n1. NEWS CATEGORY CLASSIFICATION")
print("Accuracy :", round(news_accuracy, 4))
print("Macro F1 :", round(news_macro_f1, 4))

print("\n2. CRISIS TYPE CLASSIFICATION")
print("Accuracy :", round(crisis_accuracy, 4))
print("Macro F1 :", round(crisis_macro_f1, 4))

print("\n3. URGENCY ML EXPERIMENT")
print("Accuracy :", round(urgency_accuracy, 4))
print("Macro F1 :", round(urgency_macro_f1, 4))

results = pd.DataFrame({
    "Component": [
        "News Category Classification",
        "Crisis Type Classification",
        "Urgency ML Experiment"
    ],
    "Model": [
        "TF-IDF + Logistic Regression",
        "TF-IDF + Logistic Regression",
        "TF-IDF + Logistic Regression"
    ],
    "Accuracy": [
        accuracy,
        1.0000,
        0.3235
    ],
    "Macro F1": [
        0.7849,
        1.0000,
        0.2976
    ],
    "Final Decision": [
        "Selected",
        "Selected",
        "Not selected"
    ]
})

display(results)

print("accuracy =", accuracy)
print("nb_accuracy =", nb_accuracy)

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# Create confusion matrix
news_cm = confusion_matrix(y_test, y_pred, labels=category_model.classes_)

plt.figure(figsize=(8, 6))
plt.imshow(news_cm)

plt.title("News Category Classification - Confusion Matrix")
plt.xlabel("Predicted Category")
plt.ylabel("Actual Category")

plt.xticks(
    range(len(category_model.classes_)),
    category_model.classes_,
    rotation=90
)

plt.yticks(
    range(len(category_model.classes_)),
    category_model.classes_
)

# Add numbers inside the matrix
for i in range(len(category_model.classes_)):
    for j in range(len(category_model.classes_)):
        plt.text(j, i, news_cm[i, j], ha="center", va="center")

plt.colorbar()
plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# Create crisis type confusion matrix
crisis_cm = confusion_matrix(
    y_crisis_test,
    crisis_type_pred,
    labels=crisis_type_model.classes_
)

plt.figure(figsize=(8, 6))
plt.imshow(crisis_cm)

plt.title("Crisis Type Classification - Confusion Matrix")
plt.xlabel("Predicted Crisis Type")
plt.ylabel("Actual Crisis Type")

plt.xticks(
    range(len(crisis_type_model.classes_)),
    crisis_type_model.classes_,
    rotation=45
)

plt.yticks(
    range(len(crisis_type_model.classes_)),
    crisis_type_model.classes_
)

# Add values inside the matrix
for i in range(len(crisis_type_model.classes_)):
    for j in range(len(crisis_type_model.classes_)):
        plt.text(
            j,
            i,
            crisis_cm[i, j],
            ha="center",
            va="center"
        )

plt.colorbar()
plt.tight_layout()
plt.show()

"""**Conclusion**

This project successfully uses NLP and machine learning to classify and prioritize public information. The hybrid approach provides useful predictions for news categories, crisis types, urgency, action requirements, and final priority, demonstrating the practical use of NLP in real-world information management.
"""